// Code generated by protoc-gen-go.
// source: powerLog.proto
// DO NOT EDIT!

package powerLog

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type PowerLog struct {
	Start            *int64  `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	Offset           []int32 `protobuf:"varint,2,rep,packed,name=offset" json:"offset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PowerLog) Reset()         { *m = PowerLog{} }
func (m *PowerLog) String() string { return proto.CompactTextString(m) }
func (*PowerLog) ProtoMessage()    {}

func (m *PowerLog) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *PowerLog) GetOffset() []int32 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func init() {
}
